export const FETCH_USER = 'FETCH_USER';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const UPDATE_OTHER_USER_SUCCESS = 'UPDATE_OTHER_USER_SUCCESS';
export const UPDATE_OTHER_USER_AND_COOKIE_SUCCESS = 'UPDATE_OTHER_USER_AND_COOKIE_SUCCESS';
